export const PERMISSIONS = {
  // Organization / structure
  ORG_MANAGE: 'org:manage',
  BRANCH_MANAGE: 'branch:manage',
  DEPARTMENT_MANAGE: 'department:manage',
  USER_MANAGE: 'user:manage',
  ROLE_MANAGE: 'role:manage',

  // Patients
  PATIENT_READ: 'patient:read',
  PATIENT_CREATE: 'patient:create',
  PATIENT_UPDATE: 'patient:update',

  // Appointments + OPD
  APPOINTMENT_READ: 'appointment:read',
  APPOINTMENT_MANAGE: 'appointment:manage',
  CONSULTATION_READ: 'consultation:read',
  CONSULTATION_WRITE: 'consultation:write',

  // IPD
  IPD_READ: 'ipd:read',
  IPD_MANAGE: 'ipd:manage',
  MAR_WRITE: 'mar:write',

  // Pharmacy
  PHARMACY_READ: 'pharmacy:read',
  PHARMACY_DISPENSE: 'pharmacy:dispense',
  PHARMACY_STOCK: 'pharmacy:stock',

  // Laboratory
  LAB_READ: 'lab:read',
  LAB_ORDER: 'lab:order',
  LAB_RESULT_ENTER: 'lab:result:enter',
  LAB_RESULT_VERIFY: 'lab:result:verify',

  // Hospital billing (internal only — NO Razorpay)
  BILLING_READ: 'billing:read',
  BILLING_MANAGE: 'billing:manage',
  BILLING_REFUND: 'billing:refund',

  // Platform (Super Admin only)
  PLATFORM_TENANT_MANAGE: 'platform:tenant:manage',
  PLATFORM_PLAN_MANAGE: 'platform:plan:manage',
  PLATFORM_SUBSCRIPTION_MANAGE: 'platform:subscription:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

import type { RoleCode } from './roles';

/** Default permission sets — Hospital Admin can adjust module visibility per role. */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleCode, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.PLATFORM_TENANT_MANAGE,
    PERMISSIONS.PLATFORM_PLAN_MANAGE,
    PERMISSIONS.PLATFORM_SUBSCRIPTION_MANAGE,
    // NOTE: deliberately NO hospital-scoped permission.
  ],
  HOSPITAL_ADMIN: [
    PERMISSIONS.ORG_MANAGE, PERMISSIONS.BRANCH_MANAGE, PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.USER_MANAGE, PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_READ, PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.CONSULTATION_READ, PERMISSIONS.CONSULTATION_WRITE,
    PERMISSIONS.IPD_READ, PERMISSIONS.IPD_MANAGE, PERMISSIONS.MAR_WRITE,
    PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_STOCK,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_ORDER, PERMISSIONS.LAB_RESULT_ENTER, PERMISSIONS.LAB_RESULT_VERIFY,
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_MANAGE, PERMISSIONS.BILLING_REFUND,
  ],
  DOCTOR: [
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_READ, PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.CONSULTATION_READ, PERMISSIONS.CONSULTATION_WRITE,
    PERMISSIONS.IPD_READ, PERMISSIONS.IPD_MANAGE, PERMISSIONS.MAR_WRITE,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_ORDER,
    PERMISSIONS.PHARMACY_READ,
  ],
  NURSE: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.CONSULTATION_READ,
    PERMISSIONS.IPD_READ, PERMISSIONS.IPD_MANAGE, PERMISSIONS.MAR_WRITE,
    PERMISSIONS.LAB_READ,
  ],
  RECEPTIONIST: [
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_READ, PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.BILLING_READ,
  ],
  PHARMACIST: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_STOCK,
    PERMISSIONS.BILLING_READ,
  ],
  LAB_TECHNICIAN: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_RESULT_ENTER, PERMISSIONS.LAB_RESULT_VERIFY,
  ],
  ACCOUNTANT: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_MANAGE, PERMISSIONS.BILLING_REFUND,
  ],
};
